{
  "name": "OpenWrt",
  "version": "24.10",
  "slug": "openwrt",
  "description": "OpenWrt 未完善，仅供测试,所有数据都会在重启OpenWrt后丢失",
  "arch": [
    "aarch64",
    "amd64",
    "armv7",
    "i386",
    "armhf"
  ],
  "init": false,
  "url": "https://openwrt.org/",
  "panel_icon": "mdi:router-wireless",
  "ingress": true,
  "webui": "https://[HOST]:[PORT:443]",
  "host_network": true,
  "devices": [
    "/dev/dri",
    "/dev/dri/card0",
    "/dev/dri/card1",
    "/dev/dri/renderD128",
    "/dev/vchiq",
    "/dev/video10",
    "/dev/video11",
    "/dev/video12",
    "/dev/video13",
    "/dev/video14",
    "/dev/video15",
    "/dev/video16",
    "/dev/ttyUSB0",
    "/dev/sda",
    "/dev/sdb",
    "/dev/sdc",
    "/dev/sdd",
    "/dev/sde",
    "/dev/sdf",
    "/dev/sdg",
    "/dev/nvme",
    "/dev/nvme0n1p1",
    "/dev/nvme0n1p2",
    "/dev/nvme0n1p3",
    "/dev/nvme1n1p1",
    "/dev/nvme1n1p2",
    "/dev/nvme1n1p3",
    "/dev/nvme2n1p1",
    "/dev/nvme2n1p2",
    "/dev/nvme3n1p3",
    "/dev/mmcblk",
    "/dev/fuse",
    "/dev/sda1",
    "/dev/sdb1",
    "/dev/sdc1",
    "/dev/sdd1",
    "/dev/sde1",
    "/dev/sdf1",
    "/dev/sdg1",
    "/dev/sda2",
    "/dev/sdb2",
    "/dev/sdc2",
    "/dev/sdd2",
    "/dev/sde2",
    "/dev/sdf2",
    "/dev/sdg2",
    "/dev/sda3",
    "/dev/sdb3",
    "/dev/sda4",
    "/dev/sdb4",
    "/dev/sda5",
    "/dev/sda6",
    "/dev/sda7",
    "/dev/sda8",
    "/dev/nvme0",
    "/dev/nvme1",
    "/dev/nvme2"
  ],
  "environment": {
    "TZ": "Asia/Shanghai",
    "HOME": "/data",
  }
}
