version: '3'
services:
  wechat:
    image: wechat-server:latest
    container_name: wechat-server
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - /mnt/data/supervisor/config/addon_config/wechat-server:/config/addon_config/wechat-server
      - /mnt/data/supervisor/addon_configs/wechat-server:/addon_configs/wechat-server
    expose:
      - 8888
    ports:
      - 8888:8888/tcp
    restart: always